[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["hardhat/=node_modules/hardhat/", "@openzeppelin/=node_modules/@openzeppelin/"]

[etherscan]
sepolia = { key = "${ETHERSCAN_API}" }